baseurl = "https://benchmarks.nuxeo.com/"
languageCode = "en-us"
title = "Nuxeo Benchmarks"
SectionPagesMenu = "main"
[params]
  description = "Benchmarks"
  author = "Nuxeo"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true