baseurl = "http://d3r0n26r95d4os.cloudfront.net/"
#baseurl = "https://benchmarks.nuxeo.com/"
languageCode = "en-us"
title = "Nuxeo Benchmarks"
SectionPagesMenu = "main"
[params]
  description = "Benchmarks"
  author = "Nuxeo"
