name: Upload SSH Config Artifacts

on:
  workflow_dispatch:

jobs:
  extract-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH config files
        run: |
          mkdir -p ssh_config
          echo "${{ secrets.KNOWN_HOSTS_OF_TARGET }}" > ssh_config/known_hosts
          echo "${{ secrets.CONFIG }}" > ssh_config/config

      - name: Upload SSH config files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssh-config-files
          path: ssh_config/
